### ISSUE TITLE
Chrome isn't found

### ISSUE THREAD

**Issue by martyphee** [JacobLinCool/playwright-docker#4]
I thought everything would be included in the docker image but I have to do `pnpm exec playwright install` to get it to work?

Is it pointing to the wrong directories?  Not sure what I'm doing wrong.

`.gitlab-ci.yml`
```yaml
stages:
  - test

tests:
  stage: test
  image: jacoblincool/playwright:chrome-1.47.0
  parallel: 1
  script:
    - pnpm install
    - pnpm exec playwright test

```

Error
```
 1) [setup] › auth.setup.ts:7:6 › authenticate customer ───────────────────────────────────────────
    Error: browserType.launch: Executable doesn't exist at /root/.cache/ms-playwright/chromium-1129/chrome-linux/chrome
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     pnpm exec playwright install                                        ║
    ║                                                                         ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝
```
